version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:14
    container_name: lembrai-postgres
    environment:
      POSTGRES_DB: lembrai
      POSTGRES_USER: postgres
      # A senha será definida pelo script de inicialização usando o secret
    secrets:
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    networks:
      - lembrai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do backend Spring Boot
  backend:
    build: .
    container_name: lembrai-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lembrai
      SPRING_DATASOURCE_USERNAME: postgres
      # A senha será definida pelo script de inicialização usando o secret
    secrets:
      - app_password
    networks:
      - lembrai-network
    # Não expõe a porta diretamente para o host, apenas para o Nginx

  # Serviço do Nginx como proxy reverso
  nginx:
    image: nginx:latest
    container_name: lembrai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot:/var/www/certbot
    networks:
      - lembrai-network
    depends_on:
      - backend

  # Serviço Certbot para certificados SSL (opcional)
  certbot:
    image: certbot/certbot
    container_name: lembrai-certbot
    volumes:
      - ./nginx/certbot:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    depends_on:
      - nginx

networks:
  lembrai-network:
    driver: bridge

volumes:
  postgres-data:

secrets:
  postgres_password:
    external: true
  app_password:
    external: true
